<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Surat extends MY_Controller {

    public function __construct()
    {
        parent::__construct();
        $this->require_auth(); // Secure all endpoints
        $this->load->model('Surat_model', 'surat');
    }

    /**
     * Enforce role constraint: Only ADMIN and DIREKTUR can access Surat Masuk
     */
    private function require_sekretariat()
    {
        if (!in_array($this->current_user->role, ['ADMIN', 'DIREKTUR'])) {
            $this->response(['status' => 'error', 'message' => 'Akses ditolak. Endpoint ini hanya untuk Admin dan Direktur.'], 403);
            exit();
        }
    }

    /**
     * GET /surat
     * List all surat masuk
     */
    public function index()
    {
        if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
            return $this->response(['status' => 'error', 'message' => 'Method not allowed'], 405);
        }

        $this->require_sekretariat();

        $limit = $this->input->get('limit') ? (int)$this->input->get('limit') : 100;
        $offset = $this->input->get('offset') ? (int)$this->input->get('offset') : 0;
        
        $surat = $this->surat->get_all($limit, $offset);
        
        $this->response([
            'status' => 'success',
            'data' => $surat
        ], 200);
    }
    
    /**
     * GET /surat/detail/{id}
     */
    public function detail($id = null)
    {
        if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
            return $this->response(['status' => 'error', 'message' => 'Method not allowed'], 405);
        }

        $this->require_sekretariat();

        if (!$id) {
            return $this->response(['status' => 'error', 'message' => 'ID surat dibutuhkan'], 400);
        }

        $surat = $this->surat->get_by_id($id);
        
        if ($surat) {
            $this->response(['status' => 'success', 'data' => $surat], 200);
        } else {
            $this->response(['status' => 'error', 'message' => 'Surat tidak ditemukan'], 404);
        }
    }

    /**
     * POST /surat/create
     * Create new surat + multiple file uploads
     * Needs to use FormData (multipart/form-data) instead of JSON
     */
    public function create()
    {
        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            return $this->response(['status' => 'error', 'message' => 'Method not allowed'], 405);
        }

        $this->require_sekretariat();

        // 1. Insert Surat Data
        $data = [
            // nomor_agenda is auto-generated by Trigger in DB
            'nomor_surat' => $this->input->post('nomor_surat'),
            'tanggal_surat' => $this->input->post('tanggal_surat'),
            'tanggal_terima' => $this->input->post('tanggal_terima', true) ?: date('Y-m-d'),
            'asal_surat' => $this->input->post('asal_surat'),
            'perihal' => $this->input->post('perihal'),
            'folder_id' => $this->input->post('folder_id') ?: null,
            'keterangan' => $this->input->post('keterangan'),
            'input_oleh' => $this->current_user->id
        ];

        // Basic validation
        if (empty($data['nomor_surat']) || empty($data['asal_surat']) || empty($data['perihal']) || empty($data['tanggal_surat'])) {
            return $this->response(['status' => 'error', 'message' => 'Harap isi nomor surat, asal surat, perihal, dan tanggal surat'], 400);
        }

        $this->db->trans_start();
        $surat_id = $this->surat->insert($data);

        // 2. Handle File Uploads (Multiple)
        $upload_path = FCPATH . 'uploads/surat/';
        if (!is_dir($upload_path)) {
            mkdir($upload_path, 0777, true);
        }

        $uploaded_files = [];
        if (!empty($_FILES['files']['name'][0])) {
            $filesCount = count($_FILES['files']['name']);
            for ($i = 0; $i < $filesCount; $i++) {
                $_FILES['file']['name']     = $_FILES['files']['name'][$i];
                $_FILES['file']['type']     = $_FILES['files']['type'][$i];
                $_FILES['file']['tmp_name'] = $_FILES['files']['tmp_name'][$i];
                $_FILES['file']['error']    = $_FILES['files']['error'][$i];
                $_FILES['file']['size']     = $_FILES['files']['size'][$i];
                
                // Add timestamp to ensure uniqueness
                $ext = pathinfo($_FILES['file']['name'], PATHINFO_EXTENSION);
                $new_name = time() . '_' . substr(md5(uniqid(rand(), true)), 0, 8) . '.' . $ext;

                $config['upload_path'] = $upload_path;
                $config['allowed_types'] = 'pdf|doc|docx|jpg|jpeg|png';
                $config['max_size'] = 10240; // 10MB
                $config['file_name'] = $new_name;

                $this->load->library('upload', $config);
                $this->upload->initialize($config);

                if ($this->upload->do_upload('file')) {
                    $fileData = $this->upload->data();
                    $file_db = [
                        'surat_masuk_id' => $surat_id,
                        'nama_asli' => $fileData['orig_name'],
                        'nama_file' => $fileData['file_name'],
                        'path_file' => 'uploads/surat/' . $fileData['file_name'],
                        'mime_type' => $fileData['file_type'],
                        'ukuran_bytes' => $fileData['file_size'] * 1024,
                        'upload_oleh' => $this->current_user->id
                    ];
                    $this->surat->insert_file($file_db);
                    $uploaded_files[] = $file_db;
                } else {
                    $this->db->trans_rollback();
                    return $this->response(['status' => 'error', 'message' => 'Upload error: ' . $this->upload->display_errors('', '')], 400);
                }
            }
        }

        $this->db->trans_complete();

        if ($this->db->trans_status() === FALSE) {
            $this->response(['status' => 'error', 'message' => 'Gagal menyimpan surat'], 500);
        } else {
            // Fetch complete record
            $suratData = $this->surat->get_by_id($surat_id);
            $this->response([
                'status' => 'success',
                'message' => 'Surat berhasil disimpan',
                'data' => $suratData
            ], 201);
        }
    }
}
